bibli_homepage:
    path:     /
    defaults: { _controller: BibliBundle:Default:index }


bibli_contact_home:
    path:     /contact
    defaults: { _controller: BibliBundle:Contact:indexContact }
    
    
bibli_ajouter_livre:
    path:     /ajouter-livre
    defaults: { _controller: BibliBundle:Livre:ajouter }