bibli_homepage:
    path:     /
    defaults: { _controller: BibliBundle:Default:index }


bibli_contact_home:
    path:     /contact
    defaults: { _controller: BibliBundle:Contact:indexContact }
    
bibli_consulter_liste_messages:
    path:     /employe/consulter-message
    defaults: { _controller: BibliBundle:Contact:consulterMessage }

bibli_supprimer_un_seul_message:
    path:     /employe/supprimer-message/{idMessage}
    defaults: { _controller: BibliBundle:Contact:supprimerMessage }
 
bibli_consulter_un_seul_message:
    path:     /employe/consulter-message/{idMessage}
    defaults: { _controller: BibliBundle:Contact:consulterUnMessage }
    
bibli_calcul_nombre_message:
    path:     /test
    defaults: { _controller: BibliBundle:Contact:calculNombreMessage }
    requirements:
        _method: GET
    
bibli_ajouter_livre:
    path:     /ajouter-livre
    defaults: { _controller: BibliBundle:Livre:ajouter }
    
bibli_rechercher_livre:
    path:     /rechercher-livre
    defaults: { _controller: BibliBundle:Livre:rechercheLivre }

