parameters:
    database_host: localhost
    database_port: 3306
    database_name: bibliotheque
    database_user: root
    database_password: 
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: cb7ee4cf24bd50b04fe0fd3fa8e534df04457c0f