parameters:
    database_host: 213.32.66.133
    database_port: 3306
    database_name: bibliotheque
    database_user: root
    database_password: projetWeb
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: cb7ee4cf24bd50b04fe0fd3fa8e534df04457c0f