# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        UserBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:   
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /rechercher-livre
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret%
    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mon-compte, role:  IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/rechercher-livre, role:  IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/mes-reservations, role:  IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/employe/, role: ROLE_EMPLOYE }